version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app

hooks: 
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3000
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 3000
      runas: ubuntu


